
# set -x

# Put your secret/local environment variables in .env
if [ -f ~/.env ]; then
  . ~/.env
fi

# Only run all this if the shell is interactive.
if [[ $- == *i* ]] ; then
  export IS_INTERACTIVE=true

  DOTFILES=$(dirname $(dirname $(readlink "${BASH_SOURCE[0]}")))

  export PATH="$PATH:$DOTFILES/bin"

  for file in $DOTFILES/bash/*;do
    source $file
  done

else
  export IS_INTERACTIVE=false
fi


