if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Added by Dato Launcher v2.0.2
export PATH="$PATH:/Users/amiel/anaconda/bin"

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
