source /usr/local/share/antigen/antigen.zsh

# # TODO: homebrew completions in a bundle?
# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

#   autoload -Uz compinit
#   compinit
# fi

antigen init ~/.antigenrc

export FZF_DEFAULT_COMMAND='ag -g ""'
# source "${ZSH}/custom/plugins/fzf-custom/base16-material-darker.config"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --reverse --inline-info"

export GPG_TTY=$(tty)

source ~/.zsh_aliases

DOTFILES=$(dirname $(dirname $(readlink ~/.zshrc)))
export PATH="$PATH:$DOTFILES/bin"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

unsetopt share_history



# TODO: Refactor this go stuff to somewhere

export GOBIN="$HOME/go/bin"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/.local/bin"

export COLORTERM=truecolor


[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)
