# ANTIGEN_LOG=/Users/amiel/tmp/antigen.log
source $(brew --prefix)/share/antigen/antigen.zsh

# # TODO: homebrew completions in a bundle?
# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

#   autoload -Uz compinit
#   compinit
# fi

antigen init ~/.antigenrc

export FZF_DEFAULT_COMMAND='ag -g ""'
# source "${ZSH}/custom/plugins/fzf-custom/base16-material-darker.config"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --reverse --inline-info"

export GPG_TTY=$(tty)

source ~/.zsh_aliases

DOTFILES=$(dirname $(dirname $(readlink ~/.zshrc)))
export PATH="$PATH:$DOTFILES/bin"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

unsetopt share_history



# TODO: Refactor this go stuff to somewhere
export PATH="$(brew --prefix)/bin:$PATH"
export GOBIN="$HOME/go/bin"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$(brew --prefix)/opt/python/libexec/bin"

eval "$(nodenv init -)"

export COLORTERM=truecolor


[[ $(brew --prefix)/bin/kubectl ]] && source <(kubectl completion zsh)


# TODO: Where to put this
export JQ_COLORS='0;31:0;31:1;37:0;37:0;32:1;37:1;37'
export LANG=en_US.UTF-8


  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi
